import jsPDF from 'jspdf';
import { CampaignItem } from '../types';

export const exportCampaignToPdf = (campaign: CampaignItem, reportMarkdown?: string) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let y = 14;

  // Colors
  const darkNavy = [11, 19, 43];
  const primaryBlue = [37, 99, 235];
  const textDark = [15, 23, 42];
  const textMuted = [100, 116, 139];
  const lightBg = [248, 250, 252];
  const borderGrey = [226, 232, 240];

  // Severity color helper
  const getSeverityColor = (sev: string): [number, number, number] => {
    switch (sev.toUpperCase()) {
      case 'CRITICAL':
        return [220, 38, 38]; // Red
      case 'HIGH':
        return [217, 119, 6]; // Amber
      case 'MEDIUM':
        return [37, 99, 235]; // Blue
      default:
        return [16, 185, 129]; // Emerald
    }
  };

  // Helper for adding new page with header/footer
  const checkPageBreak = (neededHeight: number) => {
    if (y + neededHeight > pageHeight - 20) {
      addFooter();
      doc.addPage();
      y = 16;
      addPageHeader();
    }
  };

  const addPageHeader = () => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text('AEGIS DEFENSE  |  FORENSIC THREAT INTELLIGENCE DOSSIER', 14, 10);
    doc.text(`CAMPAIGN ID: ${campaign.id.toUpperCase()}`, pageWidth - 14, 10, { align: 'right' });
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(14, 12, pageWidth - 14, 12);
  };

  const addFooter = () => {
    const pageCount = doc.getNumberOfPages();
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184);
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(14, pageHeight - 12, pageWidth - 14, pageHeight - 12);
    doc.text(
      'RESTRICTED INTELLIGENCE DOSSIER — GENERATED BY AEGIS INFORMATION INTEGRITY DEFENSE SUITE',
      14,
      pageHeight - 8
    );
    doc.text(`Page ${pageCount}`, pageWidth - 14, pageHeight - 8, { align: 'right' });
  };

  // ==========================================
  // PAGE 1: HEADER & BANNER
  // ==========================================
  // Top Banner Box
  doc.setFillColor(darkNavy[0], darkNavy[1], darkNavy[2]);
  doc.roundedRect(14, y, pageWidth - 28, 28, 3, 3, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(255, 255, 255);
  doc.text('THREAT INTELLIGENCE DOSSIER', 20, y + 10);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(147, 197, 253);
  doc.text('FORENSIC MULTI-FACTOR INFORMATION OPERATION REPORT', 20, y + 16);

  // Classification & Timestamp Tag
  doc.setFontSize(8);
  doc.setTextColor(203, 213, 225);
  const nowStr = new Date().toUTCString();
  doc.text(`Generated: ${nowStr}`, 20, y + 23);

  // Severity Badge in Top Banner
  const sevColor = getSeverityColor(campaign.severity);
  doc.setFillColor(sevColor[0], sevColor[1], sevColor[2]);
  doc.roundedRect(pageWidth - 58, y + 7, 44, 14, 2, 2, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(255, 255, 255);
  doc.text(
    `${campaign.severity.toUpperCase()} (${(campaign.risk_score * 100).toFixed(0)}%)`,
    pageWidth - 36,
    y + 16,
    { align: 'center' }
  );

  y += 34;

  // ==========================================
  // SECTION 1: CAMPAIGN OVERVIEW
  // ==========================================
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(primaryBlue[0], primaryBlue[1], primaryBlue[2]);
  doc.text('1. EXECUTIVE SUMMARY & TARGET SPECIFICATIONS', 14, y);
  doc.setDrawColor(primaryBlue[0], primaryBlue[1], primaryBlue[2]);
  doc.setLineWidth(0.5);
  doc.line(14, y + 2, pageWidth - 14, y + 2);
  y += 8;

  // Metadata Card
  doc.setFillColor(lightBg[0], lightBg[1], lightBg[2]);
  doc.setDrawColor(borderGrey[0], borderGrey[1], borderGrey[2]);
  doc.roundedRect(14, y, pageWidth - 28, 38, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(textDark[0], textDark[1], textDark[2]);
  doc.text(`Campaign: ${campaign.name}`, 20, y + 7);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(textMuted[0], textMuted[1], textMuted[2]);
  doc.text(`Campaign ID: ${campaign.id}`, 20, y + 13);
  doc.text(`Operational Status: ${campaign.status}`, 80, y + 13);
  doc.text(`Active Platforms: ${campaign.total_platforms}`, 140, y + 13);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(textDark[0], textDark[1], textDark[2]);
  doc.text('Stated Objective:', 20, y + 21);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(textMuted[0], textMuted[1], textMuted[2]);
  const objLines = doc.splitTextToSize(campaign.objective, pageWidth - 65);
  doc.text(objLines, 52, y + 21);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(textDark[0], textDark[1], textDark[2]);
  doc.text('Core Narrative:', 20, y + 30);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(textMuted[0], textMuted[1], textMuted[2]);
  const narLines = doc.splitTextToSize(`"${campaign.target_narrative}"`, pageWidth - 65);
  doc.text(narLines, 52, y + 30);

  y += 44;

  // ==========================================
  // SECTION 2: METRICS & TELEMETRY
  // ==========================================
  checkPageBreak(45);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(primaryBlue[0], primaryBlue[1], primaryBlue[2]);
  doc.text('2. THREAT METRICS & PROPAGATION TELEMETRY', 14, y);
  doc.setDrawColor(primaryBlue[0], primaryBlue[1], primaryBlue[2]);
  doc.setLineWidth(0.5);
  doc.line(14, y + 2, pageWidth - 14, y + 2);
  y += 8;

  // 4 Metric Boxes
  const boxWidth = (pageWidth - 28 - 9) / 4;
  const metrics = [
    { label: 'Composite Risk Score', val: `${(campaign.risk_score * 100).toFixed(0)}%`, sub: 'Multi-factor index' },
    { label: 'GNN Topology Anomaly', val: `${(campaign.gnn_risk_score * 100).toFixed(0)}%`, sub: 'GraphSAGE GNN' },
    { label: 'Audience Reach', val: campaign.total_reach.toLocaleString(), sub: 'Cross-platform audience' },
    { label: 'Velocity Rate', val: `${campaign.velocity_events_per_hour}/hr`, sub: `Branching factor: ${campaign.branching_factor}` },
  ];

  metrics.forEach((m, idx) => {
    const bx = 14 + idx * (boxWidth + 3);
    doc.setFillColor(lightBg[0], lightBg[1], lightBg[2]);
    doc.setDrawColor(borderGrey[0], borderGrey[1], borderGrey[2]);
    doc.roundedRect(bx, y, boxWidth, 24, 2, 2, 'FD');

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(textMuted[0], textMuted[1], textMuted[2]);
    doc.text(m.label, bx + boxWidth / 2, y + 6, { align: 'center' });

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(primaryBlue[0], primaryBlue[1], primaryBlue[2]);
    doc.text(m.val, bx + boxWidth / 2, y + 14, { align: 'center' });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6.5);
    doc.setTextColor(textMuted[0], textMuted[1], textMuted[2]);
    doc.text(m.sub, bx + boxWidth / 2, y + 20, { align: 'center' });
  });

  y += 30;

  // ==========================================
  // SECTION 3: EXPLAINABLE EVIDENCE
  // ==========================================
  checkPageBreak(50);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(primaryBlue[0], primaryBlue[1], primaryBlue[2]);
  doc.text('3. EXPLAINABLE FORENSIC EVIDENCE & DIAGNOSTICS', 14, y);
  doc.setDrawColor(primaryBlue[0], primaryBlue[1], primaryBlue[2]);
  doc.setLineWidth(0.5);
  doc.line(14, y + 2, pageWidth - 14, y + 2);
  y += 8;

  campaign.explainability_reasons.forEach((reason, idx) => {
    let tag = '';
    let body = reason;
    if (reason.startsWith('[')) {
      const endBracket = reason.indexOf(']');
      if (endBracket !== -1) {
        tag = reason.substring(1, endBracket);
        body = reason.substring(endBracket + 1).trim();
      }
    }

    const splitBody = doc.splitTextToSize(body, pageWidth - 55);
    const cardHeight = Math.max(14, 8 + splitBody.length * 4.2);

    checkPageBreak(cardHeight + 4);
    doc.setFillColor(lightBg[0], lightBg[1], lightBg[2]);
    doc.setDrawColor(borderGrey[0], borderGrey[1], borderGrey[2]);
    doc.roundedRect(14, y, pageWidth - 28, cardHeight, 1.5, 1.5, 'FD');

    // Bullet marker
    doc.setFillColor(primaryBlue[0], primaryBlue[1], primaryBlue[2]);
    doc.circle(20, y + 6, 2, 'F');

    if (tag) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(primaryBlue[0], primaryBlue[1], primaryBlue[2]);
      doc.text(`[${tag}]`, 26, y + 6);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(textDark[0], textDark[1], textDark[2]);
      doc.text(splitBody, 26, y + 10.5);
    } else {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(textDark[0], textDark[1], textDark[2]);
      doc.text(splitBody, 26, y + 7.5);
    }

    y += cardHeight + 3;
  });

  y += 4;

  // ==========================================
  // SECTION 4: LINKED DISSEMINATION POSTS
  // ==========================================
  if (campaign.posts && campaign.posts.length > 0) {
    checkPageBreak(55);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(primaryBlue[0], primaryBlue[1], primaryBlue[2]);
    doc.text('4. MULTI-PLATFORM DISSEMINATION POSTS', 14, y);
    doc.setDrawColor(primaryBlue[0], primaryBlue[1], primaryBlue[2]);
    doc.setLineWidth(0.5);
    doc.line(14, y + 2, pageWidth - 14, y + 2);
    y += 8;

    // Table Header
    doc.setFillColor(darkNavy[0], darkNavy[1], darkNavy[2]);
    doc.rect(14, y, pageWidth - 28, 7, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(255, 255, 255);
    doc.text('PLATFORM', 18, y + 5);
    doc.text('ACCOUNT', 50, y + 5);
    doc.text('TYPE', 90, y + 5);
    doc.text('ENGAGEMENT', 115, y + 5);
    doc.text('CONTENT SNIPPET', 145, y + 5);
    y += 7;

    campaign.posts.slice(0, 8).forEach((p, idx) => {
      checkPageBreak(12);
      const rowBg = idx % 2 === 0 ? [255, 255, 255] : lightBg;
      doc.setFillColor(rowBg[0], rowBg[1], rowBg[2]);
      doc.setDrawColor(borderGrey[0], borderGrey[1], borderGrey[2]);
      doc.rect(14, y, pageWidth - 28, 9, 'FD');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7.5);
      doc.setTextColor(primaryBlue[0], primaryBlue[1], primaryBlue[2]);
      doc.text(p.platform || 'Platform', 18, y + 6);

      doc.setFont('helvetica', 'normal');
      doc.setTextColor(textDark[0], textDark[1], textDark[2]);
      doc.text(p.account || '@actor', 50, y + 6);
      doc.text(p.post_type || 'ORIGINAL', 90, y + 6);
      doc.text(`Likes: ${p.likes} | Reshares: ${p.reshares}`, 115, y + 6);

      const snippet = (p.content_snippet || '').slice(0, 32) + '...';
      doc.setTextColor(textMuted[0], textMuted[1], textMuted[2]);
      doc.text(snippet, 145, y + 6);

      y += 9;
    });

    y += 6;
  }

  // ==========================================
  // SECTION 5: DEFENSIVE COUNTERMEASURES
  // ==========================================
  checkPageBreak(45);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(primaryBlue[0], primaryBlue[1], primaryBlue[2]);
  doc.text('5. RECOMMENDED DEFENSIVE ACTIONS & CONTAINMENT', 14, y);
  doc.setDrawColor(primaryBlue[0], primaryBlue[1], primaryBlue[2]);
  doc.setLineWidth(0.5);
  doc.line(14, y + 2, pageWidth - 14, y + 2);
  y += 8;

  const recommendations = [
    {
      title: 'Platform Quarantine & Rate Limiting',
      desc: 'Deploy automated rate limits on identified coordinated bot clusters across microblogging and channel relay bridges.',
    },
    {
      title: 'Forensic Lineage Invalidation',
      desc: 'Publish cryptographic fact-check attestations referencing origin root seeds to neutralize viral paraphrased derivatives.',
    },
    {
      title: 'Cross-Platform Entity Monitoring',
      desc: 'Track newly generated mutation variants matching high-similarity vector thresholds (>85%) in real-time feeds.',
    },
  ];

  recommendations.forEach((rec, idx) => {
    checkPageBreak(16);
    doc.setFillColor(lightBg[0], lightBg[1], lightBg[2]);
    doc.setDrawColor(borderGrey[0], borderGrey[1], borderGrey[2]);
    doc.roundedRect(14, y, pageWidth - 28, 14, 1.5, 1.5, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(primaryBlue[0], primaryBlue[1], primaryBlue[2]);
    doc.text(`${idx + 1}. ${rec.title}`, 20, y + 5.5);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(textDark[0], textDark[1], textDark[2]);
    const recText = doc.splitTextToSize(rec.desc, pageWidth - 45);
    doc.text(recText, 20, y + 10.5);

    y += 16;
  });

  // Final footer on all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addPageHeader();
    addFooter();
  }

  // Save the PDF
  const filename = `Threat_Dossier_${campaign.id}_${campaign.name.replace(/\s+/g, '_')}.pdf`;
  doc.save(filename);
};
